# Generated by Django 4.2.6 on 2023-10-16 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
